Allow user to provide *http.Client when constructing JsonApiGateway
letsencrypt-cpanel/cpanelgo pull request #5
Opened 2020-08-26 16:22 UTC by drgomesp

Fixes #4

2020-08-28 17:58 UTC, drgomesp commented
Reopened following @alexzorin's suggestion.

2020-08-29 08:24 UTC, alexzorin requested changes
Just one small change, otherwise looks good to me.

2020-08-29 08:24 UTC, alexzorin commented on example/cpanelcli.go
> +	cl, err := cpanel.NewJsonApi(hostname, username, password, insecure, nil)
As you have created a separate function, I don't think this change is needed.

2020-08-29 21:26 UTC, alexzorin commented
Thanks, applied in https://github.com/letsencrypt-cpanel/cpanelgo/commit/0da743896942d3e927a8b735c5497123d89a921d.

2020-08-29 21:26 UTC, closed without merging